# Generated by Django 2.2.4 on 2024-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, null=True, verbose_name='Preço Promo.'),
        ),
    ]
