# Generated by Django 2.2.4 on 2024-03-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20240319_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
